apiVersion: v1
kind: Service
metadata:
  name: knight-site
spec:
  type: ClusterIP
  selector:
    app: knight-site
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 3000
#   type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: knight-site
spec:
  selector:
    matchLabels:
      app: knight-site
  replicas: 2
  template:
    metadata:
      labels:
        app: knight-site
    spec:
      containers:
      - name: knight-site
        image: docker.io/ligulfzhou53/knight-site
        imagePullPolicy: Always
        env:
          - name: NEXT_PUBLIC_TREASURY_ADDRESS
            value: "CZtcUWhhrCjG46Cb3wq7fzKKkMtRgbN9HowqSwENcfWM"
          - name: NEXT_PUBLIC_CANDY_MACHINE_CONFIG
            value: "CXd9tRQ2dhBhnqjYqDDMa5JwaBjN7wW2RPKZwZPDwyxb"
          - name: NEXT_PUBLIC_CANDY_MACHINE_ID
            value: "7fiGDdRCpt9PUskkANqJJdLR8VUNkkdDfonncmq7no4h"
          - name: NEXT_PUBLIC_CANDY_START_DATE
            value: "1637193600000"
          - name: NEXT_PUBLIC_SOLANA_NETWORK
            value: "devnet"
          - name: NEXT_PUBLIC_SOLANA_RPC_HOST
            value: "https://explorer-api.devnet.solana.com"
        ports:
        - containerPort: 3000
