apiVersion: v1
kind: Service
metadata:
  name: knight-site
spec:
  type: ClusterIP
  selector:
    app: knight-site
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 3000
#   type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: knight-site
spec:
  selector:
    matchLabels:
      app: knight-site
  replicas: 2
  template:
    metadata:
      labels:
        app: knight-site
    spec:
      containers:
      - name: knight-site
        image: docker.io/ligulfzhou53/knight-site
        imagePullPolicy: Always
        env:
          - name: NEXT_PUBLIC_TREASURY_ADDRESS
            value: "CZtcUWhhrCjG46Cb3wq7fzKKkMtRgbN9HowqSwENcfWM"
          - name: NEXT_PUBLIC_CANDY_MACHINE_CONFIG
            value: "BJBnCSbLNuFTZaqZuozJmEBUqVrtBba7nGdAQLHrk1Cx"
          - name: NEXT_PUBLIC_CANDY_MACHINE_ID
            value: "w2u3npYqjJG9N92PpdD48f4jLxv8NpbXnLT1CAZTu8i"
          - name: NEXT_PUBLIC_CANDY_START_DATE
            value: "1637193600000"
          - name: NEXT_PUBLIC_SOLANA_NETWORK
            value: "mainnet-beta"
          - name: NEXT_PUBLIC_SOLANA_RPC_HOST
            value: "https://solana-api.projectserum.com/"
        ports:
        - containerPort: 3000
