export const NEXT_PUBLIC_TREASURY_ADDRESS=process.env.NEXT_PUBLIC_TREASURY_ADDRESS || "CZtcUWhhrCjG46Cb3wq7fzKKkMtRgbN9HowqSwENcfWM"
export const NEXT_PUBLIC_CANDY_MACHINE_CONFIG=process.env.NEXT_PUBLIC_CANDY_MACHINE_CONFIG || "9A7inKLmvWo5rAGmVzZZbjCaSDV43uX6RPiZ5Z6oi8xN"
export const NEXT_PUBLIC_CANDY_MACHINE_ID=process.env.NEXT_PUBLIC_CANDY_MACHINE_ID || "9R7whKtGFfnZ1dV65XLP45yKoGCACbnBjdCoDsZEKBHG"
export const NEXT_PUBLIC_CANDY_START_DATE=process.env.NEXT_PUBLIC_CANDY_START_DATE || "1636848000000"
export const NEXT_PUBLIC_SOLANA_NETWORK=process.env.NEXT_PUBLIC_SOLANA_NETWORK || "devnet"
export const NEXT_PUBLIC_SOLANA_RPC_HOST=process.env.NEXT_PUBLIC_SOLANA_RPC_HOST || "https://explorer-api.devnet.solana.com"

// authority = TREASURY_ADDRESS
// candyMachineAddress = CANDY_MACHINE_ID
