export const NEXT_PUBLIC_TREASURY_ADDRESS=process.env.NEXT_PUBLIC_TREASURY_ADDRESS || "CZtcUWhhrCjG46Cb3wq7fzKKkMtRgbN9HowqSwENcfWM"
export const NEXT_PUBLIC_CANDY_MACHINE_CONFIG=process.env.NEXT_PUBLIC_CANDY_MACHINE_CONFIG || "8E3J9Nguj2nQsB5Tx23AbEtjZAumW4gvgbpX5pfLsgna"
export const NEXT_PUBLIC_CANDY_MACHINE_ID=process.env.NEXT_PUBLIC_CANDY_MACHINE_ID || "EFqr576bkXYuLL8zAp9icKGA5W7TWyjpHWF7TFk2m3pw"
export const NEXT_PUBLIC_CANDY_START_DATE=process.env.NEXT_PUBLIC_CANDY_START_DATE || "1637193600000"
export const NEXT_PUBLIC_SOLANA_NETWORK=process.env.NEXT_PUBLIC_SOLANA_NETWORK || "devnet"
export const NEXT_PUBLIC_SOLANA_RPC_HOST=process.env.NEXT_PUBLIC_SOLANA_RPC_HOST || "https://explorer-api.devnet.solana.com"

// authority = TREASURY_ADDRESS
// candyMachineAddress = CANDY_MACHINE_ID
